/**/offboard_node:
  ros__parameters:
    offboard_control_mode_topic: /fmu/in/offboard_control_mode
    trajectory_setpoint_topic: /fmu/in/trajectory_setpoint
    vehicle_command_topic: /fmu/in/vehicle_command
    vehicle_local_position_topic: /fmu/out/vehicle_local_position
    vehicle_status_topic: /fmu/out/vehicle_status_v1
    acceleration_control_topic: /uav/acceleration_control

/**/landing_target_pose_node:
  ros__parameters:
    landing_target_pose_topic: /fmu/in/landing_target_pose
    vehicle_status_topic: /fmu/out/vehicle_status_v1

/**/actuator_control_node:
  ros__parameters:
    actuation_server_name: /uav/tins/actuation
    px4_address: udpin://0.0.0.0:14540
    timeout: 5.0
    actuation_indexes: [1, 2]
